#!/usr/bin/perl -CSDA -n
use HTML::Entities;
 
if (/&#/) {
	$line = decode_entities($_);
	chomp($_);
	# print STDERR "munging $_ => $line";
} else {
 	$line = $_;
}

$line=~s/http:\/\/dev[\-\.]+/http:\/\//;
$line=~s/http:\/\/www[\-\.]+/http:\/\//;
$line=~s/([\w\-]+).mandala\.library\.virginia\.edu/mandala-$1/g;
$line=~s/mandala\.library\.virginia\.edu/mandala/g;
$line=~s/\.internal\.lib\.virginia\.edu//g;
$line=~s/\.shanti\.virginia\.edu//g;
$line=~s/\/\/audio\-video/\/\/mandala-av/g;
$line=~s/([\w\-]+)\-dev/$1/;
# $line=~s/av\.mandala\.library\.virginia\.edu/av/;
# $line=~s/av\.internal\.lib\.virginia\.edu/av/g;
# $line=~s/texts\.mandala\.library\.virginia\.edu/texts/;
# $line=~s/texts\.internal\.lib\.virginia\.edu/texts/;
# $line=~s/mandala[-]//;
# $line=~s/\.shanti//;
# $line=~s/-dev\././g;

print $line;
